### PR TITLE
Added wallet balance API call.

### PR DESCRIPTION
**Pull request by zegerhoogeboom**
Added wallet balance API call as described at https://api.itbit.com/docs#trading-get-wallet-balance-get

### CODE REVIEW

**Comment by naddison36** [comment]
Thanks for this PR. I've merged and published to npm v0.0.11

**Comment by zegerhoogeboom** [comment]
Holy cow that was fast, thanks! Personally I'm more in favor of Promise style libraries so I went ahead and moved this library from callbacks to promises for myself but this is quite a breaking change for you to publish I guess. If you're any interested in another PR please have a look, I also updated the `README` @ https://github.com/zegerhoogeboom/itbit.

**edit**   
I see my [commit](https://github.com/zegerhoogeboom/itbit/commit/4f95477a48fcf0a2f305273fefa2c060a6c7f1a1)'s auto formatter made the changelog completely unreadable, sorry about that, the `README` should make clear what the changes entail though.

**Comment by naddison36** [comment]
Agree, I now prefer promises - especially with async/await.

I haven't converted this lib as I no longer use itbit. I've added you as a collaborator so feel free to pull in your PR. Just make the new version 1.0.0 so it's clear its a breaking change.

Thanks
Nick

**Comment by zegerhoogeboom** [comment]
Very sorry for the late reply! Will pull it in and publish as 1.0.0!
Thanks,
Zeger

**Pull request merged**
